### ISSUE TITLE
Update to Ember Data 2.8.beta-x and begin using improved ajax functions

### ISSUE THREAD

**Issue by BrianSipple** [elwayman02/ember-data-twitch#22]
As of Ember Data 2.7.beta-x, I've been seeing warnings in the console about `ajaxOptions` being deprecated in future releases. This is due to the [upcoming API for improved ajax functions](http://emberjs.com/blog/2016/07/25/ember-data-2-7-released.html#toc_code-ds-improved-ajax-code-a-href-https-github-com-emberjs-data-pull-3099-3099-a) that's been in beta for two releases now, and I think we'd benefit a lot by implementing the right changes now at the root adapter level so that everything else can extend from the same pattern in the future.

**Comment by elwayman02** [comment]
Seems good!

**Comment by elwayman02** [comment]
Let's make resolving this a blocker for implementing our first working endpoint, so that we make sure to do it right.

**Comment by BrianSipple** [comment]
This should be covered now that we've merged #27.
