### ISSUE TITLE
[Demo] Make sidenav toggleable/responsive

### ISSUE THREAD

**Issue by BrianSipple** [elwayman02/ember-data-twitch#36]
The sidenav should slide in and out so that users have the option to view the full page without it. Users should be able to control this manually via an icon, and we should also have some breakpoint logic that closes it by default on narrow viewports.

**Comment by elwayman02** [comment]
Is this issue resolve @BrianSipple?

**Comment by BrianSipple** [comment]
Ah, yep -- #38 was meant to cover it.
